# Generated by Django 5.1.4 on 2024-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('document', 'Document'), ('textbook', 'Textbook'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('historical', 'Historical')], max_length=100),
        ),
    ]
